#!/usr/bin/env python3
"""Export the current SPIRAL research state as a single markdown research report.

Deterministic (no LLM). This report is the comparison artifact for RQ1: the same
format is what baseline deep-research outputs are compared against.

Usage:
  python scripts/export_report.py [--blind] [-o eval/report.md]
  --blind  omit SPIRAL-identifying metadata (for rubric judging)
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load(p: str):
    return json.loads((ROOT / p).read_text())


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--blind", action="store_true")
    ap.add_argument("-o", "--out", default="eval/report.md")
    args = ap.parse_args()

    meta = load("state/meta.json")
    index = load("state/knowledge/index.json")
    graph = load("state/issues/graph.json")
    scores = load("state/assessments/scores.json").get("scores", {})

    src = {s["id"]: s for s in index.get("sources", [])}
    lines: list[str] = []
    t = meta["topic"]

    lines.append(f"# {t['title']}\n")
    if not args.blind:
        lines.append(f"*Generated by SPIRAL, cycle {meta['cycle']}.*\n")
    lines.append(f"**Scope.** {t['scope']}\n")

    issues = graph.get("issues", [])
    order = sorted(issues, key=lambda i: -scores.get(i["id"], {}).get("score", 0))

    lines.append("## Findings by issue\n")
    for iss in order:
        sc = scores.get(iss["id"], {})
        lines.append(f"### {iss['title']}\n")
        if sc and not args.blind:
            lines.append(f"*Resolution level: {sc.get('score', '?')}/5 — {sc.get('rationale', '')}*\n")
        supported = [c for c in iss.get("candidate_resolutions", []) if c.get("status") == "supported"]
        rejected = [c for c in iss.get("candidate_resolutions", []) if c.get("status") == "rejected"]
        proposed = [c for c in iss.get("candidate_resolutions", []) if c.get("status") == "proposed"]
        for c in supported:
            cites = ", ".join(f"[{e}]" for e in c.get("evidence", []))
            lines.append(f"- **Supported:** {c['summary']} {cites}")
        for c in proposed:
            cites = ", ".join(f"[{e}]" for e in c.get("evidence", []))
            lines.append(f"- Proposed (unconfirmed): {c['summary']} {cites}")
        for c in rejected:
            lines.append(f"- Rejected: {c['summary']}")
        oq = iss.get("open_questions", [])
        if oq:
            lines.append("\n**Open questions:**")
            lines.extend(f"- {q}" for q in oq)
        deps = iss.get("depends_on", [])
        if deps:
            titles = {i["id"]: i["title"] for i in issues}
            lines.append(f"\n*Depends on: {', '.join(titles.get(d, d) for d in deps)}*")
        lines.append("")

    contras = [c for c in graph.get("contradictions", []) if c.get("resolved_cycle") is None]
    if contras:
        lines.append("## Unresolved contradictions\n")
        for c in contras:
            lines.append(f"- ({c['issue_id']}) {c['description']}")
        lines.append("")

    lines.append("## Sources\n")
    for s in index.get("sources", []):
        lines.append(f"- [{s['id']}] {s['title']} — {s['url']} ({s['type']})")

    out = ROOT / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(issues)} issues, {len(src)} sources)")


if __name__ == "__main__":
    main()
